/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-tertiary-container": "#fffbff",
        "surface-dim": "#cbdbf5",
        "tertiary": "#924700",
        "tertiary-fixed": "#ffdcc6",
        "surface-container": "#e5eeff",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#424754",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#adc6ff",
        "inverse-primary": "#adc6ff",
        "primary": "#0058be",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#001a42",
        "surface-container-high": "#dce9ff",
        "background": "#ffffff",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#311400",
        "inverse-surface": "#213145",
        "surface-tint": "#005ac2",
        "on-secondary-container": "#586377",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "primary-container": "#2170e4",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-container": "#d5e0f8",
        "surface-variant": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b75b00",
        "surface": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "outline-variant": "#c2c6d6",
        "on-secondary-fixed": "#111c2d",
        "tertiary-fixed-dim": "#ffb786",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "outline": "#727785",
        "error": "#ba1a1a",
        "secondary-fixed": "#d8e3fb",
        "on-tertiary-fixed-variant": "#723600",
        "secondary": "#545f73"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "16px",
        "stack-lg": "48px",
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "gutter": "24px"
      },
      "fontFamily": {
        "headline-xl": ["Hanken Grotesk"],
        "code-sm": ["JetBrains Mono"],
        "label-md": ["JetBrains Mono"],
        "headline-lg": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "code-block": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "label-caps": ["JetBrains Mono"]
      },
      "fontSize": {
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "code-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.7", "fontWeight": "400"}],
        "code-block": ["13px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-caps": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
